# docker compose up --build --no-deps --force-recreate --remove-orphans
services:
  vulnerabilities:
    container_name: vulnerabilities-react
    build:
      context: .
      dockerfile: ./vulnerabilities.Dockerfile
    networks:
      - local_network
    volumes:
      - .:/app
      - .vulnerabilities:/.vulnerabilities
      - /app/.jenkins_configuration
      - /app/node_modules
    restart: unless-stopped

  jenkins:
    container_name: jenkins-react
    build:
      context: .
      dockerfile: ./jenkins.Dockerfile
    privileged: true
    user: root
    networks:
      - local_network
    ports:
      - "8080:8080" # Access UI at http://localhost:8080
      - "50000:50000"
    environment:
      ENV: local
      JAVA_OPTS: -Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    volumes:
      - .:/app
      - .jenkins_configuration:/var/jenkins_home
      - /app/.jenkins_configuration
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-react
    ports:
      - "9090:9090" # Access UI at http://localhost:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Mount config file
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter-react
    ports:
      - "9100:9100" # Exposes hardware/OS metrics
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-react
    ports:
      - "3000:3000" # Access UI at http://localhost:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default login: admin / admin
    restart: unless-stopped

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    networks:
      - local_network
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    networks:
      - local_network
    ports:
      - 5672:5672  # AMQP port
      - 15672:15672 # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --bind 0.0.0.0
    networks:
      - local_network
    ports:
      # - 127.0.0.1:6379:6379
      - 0.0.0.0:6379:6379

  backend:
    container_name: backend-react
    networks:
      - local_network
    build:
      # https://gitlab.com/LarryGeorges-Muala/hotel-booking-backend-django
      context: ../../hotel-booking-backend-django/
      dockerfile: ./backend.Dockerfile
    volumes:
      - ../../hotel-booking-backend-django/:/app
      - /app/.jenkins_configuration
    environment:
      ENV: ${ENVIRONMENT}
      SECRET_KEY: ${SECRET_KEY}
      REDIS_HOST: ${REDIS_HOST}
      SENTRY_DNS_DJANGO: ${SENTRY_DNS_DJANGO}
    ports:
      - 8000:8000
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started

  frontend:
    container_name: frontend-react
    networks:
      - local_network
    build:
      context: .
      dockerfile: ./frontend.Dockerfile
    volumes:
      - .:/app
      - /app/.jenkins_configuration
      - /app/node_modules  # Prevents local node_modules from overwriting container's
    environment:
      - CHOKIDAR_USEPOLLING=true  # Required for some OS/Docker setups to detect changes
      - VITE_ENV=${ENVIRONMENT}
      - VITE_BACKEND=${REACT_BACKEND_URL}
      - VITE_SENTRY_DNS=${SENTRY_DNS_REACT}
    ports:
      - 5173:5173
    depends_on:
      backend-django:
        condition: service_started

  nuclei:
    image: projectdiscovery/nuclei:latest
    container_name: nuclei-dast-react
    entrypoint: 
      - /bin/sh
      - -c
      - |
        rm -rf /.vulnerabilities/* \
        && nuclei -verbose \
          -list /app/dast.urls.txt \
          -output /.vulnerabilities/nuclei.batteringram.log \
          -trace-log /.vulnerabilities/nuclei.batteringram.trace.log \
          -error-log /.vulnerabilities/nuclei.batteringram.error.log \
          -store-resp-dir /.vulnerabilities/nuclei.batteringram.report \
          -stats \
          -timestamp \
          -matcher-status \
          -debug \
          -debug-req \
          -debug-resp \
          -attack-type batteringram \
        && nuclei -verbose \
          -list /app/dast.urls.txt \
          -output /.vulnerabilities/nuclei.pitchfork.log \
          -trace-log /.vulnerabilities/nuclei.pitchfork.trace.log \
          -error-log /.vulnerabilities/nuclei.pitchfork.error.log \
          -store-resp-dir /.vulnerabilities/nuclei.pitchfork.report \
          -stats \
          -timestamp \
          -matcher-status \
          -debug \
          -debug-req \
          -debug-resp \
          -attack-type pitchfork \
        && nuclei -verbose \
          -list /app/dast.urls.txt \
          -output /.vulnerabilities/nuclei.clusterbomb.log \
          -trace-log /.vulnerabilities/nuclei.clusterbomb.trace.log \
          -error-log /.vulnerabilities/nuclei.clusterbomb.error.log \
          -store-resp-dir /.vulnerabilities/nuclei.clusterbomb.report \
          -stats \
          -timestamp \
          -matcher-status \
          -debug \
          -debug-req \
          -debug-resp \
          -attack-type clusterbomb
    volumes:
      - .:/app
      - .vulnerabilities:/.vulnerabilities
      - /app/.jenkins_configuration
      - /app/node_modules
    depends_on:
      frontend:
        condition: service_started

networks:
  local_network:
    driver: bridge
