apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'booking-frontend'
spec:
  destination:
    name: 'in-cluster'
    namespace: 'dev'
  source:
    path: '.argo-cd/chart'
    repoURL: 'https://github.com/LarryGeorges-Muala/hotel-booking-frontend-reactjs'
    targetRevision: HEAD
    helm:
      parameters:
      - name: "super-chart.deployments[0].containers[0].image.tag"
        value: "$ARGOCD_APP_REVISION"
      valueFiles:
      - values.yaml
  project: 'default'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
